### ISSUE TITLE
Allow and disallow routes

### ISSUE THREAD

**Issue by bertoost** [ricbra/robots-txt-bundle#2]
First off; nice little bundle!
But maybe good to make it even more configurable? Something like;

```
ricbra_robots_txt:
    allow_robots: %allow_robots%
    disallow_routes:
        - my_custom.route_name1
        - my_custom.route_name2
        - my_custom.route_name3
```

This would generate a robots.txt with a following format;

```
User-agent: *
Disallow: /url/path/of/my/first_route
Disallow: /url/path/of/my/second_route
Disallow: /url/path/of/my/third_route
```

I don't think "allow_routes" is necessary here?

Also I don't know for sure, but when you configure "allow_robots: false" it should also not print "Disallow: " without anything in the robots.txt route?

**Comment by ricbra** [comment]
I like the idea of blacklisting specific routes. However I think we also need to change the configuration format a bit. The <code>allow_robots</code> key is just a shortcut to allow or disallow <code>/</code>. If you add other routes to your config, things can get confusing:

``` yml
ricbra_robots_txt:
    allow_robots: false
    disallow_routes:
        - my_custom.route_name1
        - my_custom.route_name2
        - my_custom.route_name3
```

Would result in:

```
# www.robotstxt.org/
# www.google.com/support/webmasters/bin/answer.py?hl=en&answer=156449

User-agent: *
Disallow: /
Disallow: /other-route
Disallow: /more-routes
```

Personally I would opt for the following new configuration format which covers every possible situation supported in robots.txt (where <code>route</code> or <code>path</code> is required, <code>user-agent</code> is optional and defaults to <code>*</code>:

``` yml
ricbra_robots_txt:
    disallow_routes:
    - { route: my_custom.route_name1, user-agent: "Googlebot-Image" }
    - { path: "/this-is-not-a-route/test.jpg" }
```

Would result in:

```
# www.robotstxt.org/
# www.google.com/support/webmasters/bin/answer.py?hl=en&answer=156449

User-agent: Googlebot-Image
Disallow: /my-custom-route

User-agent: *
Disallow: /this-is-not-a-route/test.jpg
```

Empty config:

``` yml
ricbra_robots_txt:
    disallow_routes: []
```

Gives:

```
# www.robotstxt.org/
# www.google.com/support/webmasters/bin/answer.py?hl=en&answer=156449

Disallow: 
```

And for blacklisting everything:

``` yml
ricbra_robots_txt:
    disallow_routes:
    - { path: "/" }
```

What do you think of my proposal? I'm quite busy at the moment, so would be cool if you want to work on these improvements. 

Regarding your last point: I've did some research and on http://www.robotstxt.org/robotstxt.html you can see this syntax is valid.

**Comment by bertoost** [comment]
Sounds very good! :+1: 
The allow_roots indeed is weird in this case, but in order to stay backwards compatible?

**Comment by ricbra** [comment]
Well we're not stable yet so it's ok to break BC but we could still support the old way. So this configuration:

``` yml
ricbra_robots_txt:
    allow_robots: false
```

Would (still) result in:

```
# www.robotstxt.org/
# www.google.com/support/webmasters/bin/answer.py?hl=en&answer=156449

Disallow: /
```

But if people gonna mix old and new style of configuration we should throw an exception:

``` yml
ricbra_robots_txt:
    allow_robots: false
    disallow_routes:
    - { path: "/" } 
```
